name: Install mxpy using erdpy-up (MacOS)

on:
  pull_request:
    branches: [main, feat/*]
  workflow_dispatch:

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  install-mxpy:
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          wget -O erdpy-up.py https://raw.githubusercontent.com/multiversx/mx-sdk-erdpy/$BRANCH_NAME/erdpy-up.py
          python3 erdpy-up.py --from-branch $BRANCH_NAME <<< "2"
      - name: Smoke test
        run: |
          source /Users/runner/.bash_profile
          erdpy --version
