name: Install erdpy using erdpy-up (Ubuntu)

on:
  pull_request:
    branches: [main, development]
  workflow_dispatch:

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  install-erdpy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          wget -O erdpy-up.py https://raw.githubusercontent.com/ElrondNetwork/elrond-sdk-erdpy/$BRANCH_NAME/erdpy-up.py
          python3 erdpy-up.py --from-branch $BRANCH_NAME
      - name: Smoke test
        run: |
          source /home/runner/.profile
          erdpy --version
