name: Test localnet-dependent tests

on:
  pull_request:
    branches: [main, feat/*]
  workflow_dispatch:

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  localnet:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#        TODO: enable mac-os back once debugging is done.
#        os: [ubuntu-latest, macos-latest]
        os: [ubuntu-latest]
        python-version: [3.11]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker image
        run: |
          docker build --build-arg PYTHON_VERSION=${{ matrix.python-version }} -t mxpy .

      - name: Deploy a localnet
        run: |
          docker run -d -p 7950:7950 mxpy localnet start

      - name: Test localnet dependent tests
        run: |
          pytest -m require_localnet multiversx_sdk_cli/tests
