name: Test localnet-dependent tests

on:
  pull_request:
    branches: [main, feat/*]
  workflow_dispatch:

env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  localnet:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.11]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
          pip3 install -r ./requirements-dev.txt --upgrade

      - name: Set up MultiversX localnet
        run: |
          # Start the local testnet with mxpy
          python3 -m multiversx_sdk_cli.cli localnet setup --configfile=${GITHUB_WORKSPACE}/localnet.toml
          nohup python3 -m multiversx_sdk_cli.cli localnet start --configfile=${GITHUB_WORKSPACE}/localnet.toml > localnet.log 2>&1 & echo $! > localnet.pid
          sleep 120 # Allow time for the testnet to fully start

      - name: Test localnet dependent tests
        run: |
           pytest -m require_localnet multiversx_sdk_cli/tests
